INSERT INTO assets (id, symbol, name, asset_type, source) VALUES
  ('underlying:KRX 삼성전자 선물 레버리지 지수', 'KRX 삼성전자 선물 레버리지 지수', 'KRX 삼성전자 선물 레버리지 지수', 'futures-index', 'product-master-unverified-series'),
  ('underlying:KRX 삼성전자 레버리지 지수', 'KRX 삼성전자 레버리지 지수', 'KRX 삼성전자 레버리지 지수', 'spot-index', 'product-master-unverified-series'),
  ('underlying:KRX 삼성전자 TR 레버리지 지수', 'KRX 삼성전자 TR 레버리지 지수', 'KRX 삼성전자 TR 레버리지 지수', 'spot-index', 'product-master-unverified-series'),
  ('underlying:KRX 삼성전자 선물 인버스 -2X 지수', 'KRX 삼성전자 선물 인버스 -2X 지수', 'KRX 삼성전자 선물 인버스 -2X 지수', 'futures-index', 'product-master-unverified-series'),
  ('underlying:KRX SK하이닉스 선물 레버리지 지수', 'KRX SK하이닉스 선물 레버리지 지수', 'KRX SK하이닉스 선물 레버리지 지수', 'futures-index', 'product-master-unverified-series'),
  ('underlying:KRX SK하이닉스 레버리지 지수', 'KRX SK하이닉스 레버리지 지수', 'KRX SK하이닉스 레버리지 지수', 'spot-index', 'product-master-unverified-series'),
  ('underlying:KRX SK하이닉스 TR 레버리지 지수', 'KRX SK하이닉스 TR 레버리지 지수', 'KRX SK하이닉스 TR 레버리지 지수', 'spot-index', 'product-master-unverified-series'),
  ('underlying:KRX SK하이닉스 선물 인버스 -2X 지수', 'KRX SK하이닉스 선물 인버스 -2X 지수', 'KRX SK하이닉스 선물 인버스 -2X 지수', 'futures-index', 'product-master-unverified-series'),
  ('product:0198B0', '0198B0', '1Q 삼성전자선물단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0194N0', '0194N0', 'KIWOOM 삼성전자선물단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0193W0', '0193W0', 'KODEX 삼성전자단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0195R0', '0195R0', 'TIGER 삼성전자단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0194M0', '0194M0', 'ACE 삼성전자단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0192M0', '0192M0', 'RISE 삼성전자단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0193K0', '0193K0', 'PLUS 삼성전자단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:520100', '520100', '미래에셋 레버리지 삼성전자 단일종목 ETN', 'ETN', 'fsc-securities-product'),
  ('product:0193L0', '0193L0', 'PLUS 삼성전자선물단일종목인버스2X', 'ETF', 'fsc-securities-product'),
  ('product:0194R0', '0194R0', 'KIWOOM SK하이닉스선물단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0198D0', '0198D0', '1Q SK하이닉스선물단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0193T0', '0193T0', 'KODEX SK하이닉스단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0195S0', '0195S0', 'TIGER SK하이닉스단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0197W0', '0197W0', 'SOL SK하이닉스단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0194T0', '0194T0', 'ACE SK하이닉스단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:0192L0', '0192L0', 'RISE SK하이닉스단일종목레버리지', 'ETF', 'fsc-securities-product'),
  ('product:520101', '520101', '미래에셋 레버리지 SK하이닉스 단일종목ETN', 'ETN', 'fsc-securities-product'),
  ('product:0197X0', '0197X0', 'SOL SK하이닉스선물단일종목인버스2X', 'ETF', 'fsc-securities-product')
ON CONFLICT(id) DO UPDATE SET
  symbol = excluded.symbol,
  name = excluded.name,
  asset_type = excluded.asset_type,
  source = excluded.source,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (code, asset_id, name, product_type, leverage, underlying_id, underlying_type, listed_date, analysis_capability, active, catalog_scope, verification_status, evidence_url, verified_at) VALUES
  ('0198B0', 'product:0198B0', '1Q 삼성전자선물단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 선물 레버리지 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0194N0', 'product:0194N0', 'KIWOOM 삼성전자선물단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 선물 레버리지 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0193W0', 'product:0193W0', 'KODEX 삼성전자단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0195R0', 'product:0195R0', 'TIGER 삼성전자단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0194M0', 'product:0194M0', 'ACE 삼성전자단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0192M0', 'product:0192M0', 'RISE 삼성전자단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0193K0', 'product:0193K0', 'PLUS 삼성전자단일종목레버리지', 'ETF', 2, 'underlying:KRX 삼성전자 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('520100', 'product:520100', '미래에셋 레버리지 삼성전자 단일종목 ETN', 'ETN', 2, 'underlying:KRX 삼성전자 TR 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://kind.krx.co.kr/disclosure/etnisudetail.do?method=searchEtnIsuSummary&strIsuSrtCd=Q520100', '2026-08-26'),
  ('0193L0', 'product:0193L0', 'PLUS 삼성전자선물단일종목인버스2X', 'ETF', -2, 'underlying:KRX 삼성전자 선물 인버스 -2X 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://kind.krx.co.kr/disclosure/etfisudetail.do?method=searchEtfIsuSummary&strIsurCd=0193L', '2026-08-26'),
  ('0194R0', 'product:0194R0', 'KIWOOM SK하이닉스선물단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 선물 레버리지 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0198D0', 'product:0198D0', '1Q SK하이닉스선물단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 선물 레버리지 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0193T0', 'product:0193T0', 'KODEX SK하이닉스단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0195S0', 'product:0195S0', 'TIGER SK하이닉스단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0197W0', 'product:0197W0', 'SOL SK하이닉스단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0194T0', 'product:0194T0', 'ACE SK하이닉스단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('0192L0', 'product:0192L0', 'RISE SK하이닉스단일종목레버리지', 'ETF', 2, 'underlying:KRX SK하이닉스 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.samsungpop.com/ux/kor/customer/notice/notice/noticeViewContent.do?MenuSeqNo=23968', '2026-08-26'),
  ('520101', 'product:520101', '미래에셋 레버리지 SK하이닉스 단일종목ETN', 'ETN', 2, 'underlying:KRX SK하이닉스 TR 레버리지 지수', 'spot-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://kind.krx.co.kr/external/2026/05/22/000553/20260522001367/68342.htm', '2026-08-26'),
  ('0197X0', 'product:0197X0', 'SOL SK하이닉스선물단일종목인버스2X', 'ETF', -2, 'underlying:KRX SK하이닉스 선물 인버스 -2X 지수', 'futures-index', '2026-05-27', 'actual-only', 1, 'production', 'verified', 'https://www.soletf.co.kr/ko/fund/etf/211114?tabIndex=3', '2026-08-26')
ON CONFLICT(code) DO UPDATE SET
  asset_id = excluded.asset_id,
  name = excluded.name,
  product_type = excluded.product_type,
  leverage = excluded.leverage,
  underlying_id = excluded.underlying_id,
  underlying_type = excluded.underlying_type,
  listed_date = excluded.listed_date,
  analysis_capability = excluded.analysis_capability,
  active = excluded.active,
  catalog_scope = excluded.catalog_scope,
  verification_status = excluded.verification_status,
  evidence_url = excluded.evidence_url,
  verified_at = excluded.verified_at,
  updated_at = CURRENT_TIMESTAMP;
